### ISSUE TITLE
PIL.UnidentifiedImageError: cannot identify image file

### ISSUE THREAD

**Issue by mmagdy88** [victordomingos/optimize-images#22]
Hello,

This issue is similar to #13 

I try to use optimize-images cli on Ubuntu to recursively optimize images, it happens suddenly that I get this error:

> PIL.UnidentifiedImageError: cannot identify image file

when I try to only optimize the image in question I get the same error, so the error is in the image itself, when I check its type and details I get that:
`JPEG image data, JFIF standard 1.01, resolution (DPI), density 96x96, segment length 16, Exif Standard: [TIFF image data, big-endian, direntries=23, height=0, bps=0, compression=LZW, PhotometricIntepretation=RGB, manufacturer=Canon, model=Canon EOS 5DS R, orientation=upper-left, width=0]`

```
# python -V
Python 3.6.10
```

```
# optimize-images -v
1.3.5
```

```
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
```

My question here, why the software refusing to optimize this image and how can I make it ignore and continue because if it finds an error it just stops, I want it to ignore that error and continue working on the rest.

Best regards,

**Comment by victordomingos** [comment]
Hi! It may have something to do with the file format being used. The intended behavior for the current version is to optimize any supported images (currently JPEG and PNG), and simply skip the others. The error you mentioned should not be displayed to the user, at least in that form.

If you can provide a sample file thy produces that error, it will help us.

**Comment by mmagdy88** [comment]
Sure thing, you can download it below:
https://www.mediafire.com/file/hp94bww54pcepoq/Cami_Dress_Short_2_M4559-White.zip/file

**Comment by victordomingos** [comment]
Thanks for your report and for providing the file for further testing.

The image file seems to be either corrupt or in an unsupported format. Probably the first. I am not able to open it in an image editor, and ImageMagick reports the following:

```
$ identify -verbose /Users/victor/Downloads/Cami\ Dress\ Short\ 2\ M4559-White.jpg
identify: Corrupt JPEG data: 730 extraneous bytes before marker 0x9c `/Users/victor/Downloads/Cami Dress Short 2 M4559-White.jpg' @ warning/jpeg.c/JPEGWarningHandler/398.
identify: Unsupported marker type 0x9c `/Users/victor/Downloads/Cami Dress Short 2 M4559-White.jpg' @ error/jpeg.c/JPEGErrorHandler/342.
```

Either way, the expected behaviour is to keep going with the next file, so this exception should be properly handled. I have just committed a quick fix that makes the application silently continue, with no error. I hope it helps. In case any issues persist please let me know.

I understand it would be a good idea to implement some kind of indication or logging to let the user know which images for some reason were not supported. I may think about it later, but right now I can't focus on that task.

**Comment by mmagdy88** [comment]
Sorry for reopening, thanks for applying the quick fix, however, when I tried to uninstall and reinstall optimize-images using pip3 using the commands below:

```
pip3 uninstall optimize-images
pip3 install optimize-images
```

I tried this as well

`pip3 install optimize-images --upgrade`

The issue still there, didn't I upgrade it correctly or I'm missing something?

**Comment by victordomingos** [comment]
It’s not yet on PyPI. You can grab the latest version from GitHub and install it temporarily in development mode. There is more information in our [documentation](https://github.com/victordomingos/optimize-images/blob/master/docs/docs_EN.md) (please see the section “Installing the most recent development version”).

**Comment by mmagdy88** [comment]
Did it and worked like a charm, thank you!
